"""create_user_settings_table

Revision ID: 3d52fe0cf85b
Revises: 246951a4ef9a
Create Date: 2026-09-28 18:30:14.006396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d52fe0cf85b'
down_revision: Union[str, None] = '246951a4ef9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('appearance', sa.JSON(), nullable=True),
    sa.Column('diary_preferences', sa.JSON(), nullable=True),
    sa.Column('notifications', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
